### ISSUE TITLE
Prüfen, ob die erste Unit eines Tests ein Freigabewort erfordert --> Fehlermeldung!

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#112]
Friegabe-Wort-Modal: Gibt ein falsches Freigabewort ein, erscheint eine Snackbar-Meldung, die sagt dass es nicht korrekt war mit einem Button "Freigabewort" - clickt man auf den Button oder wartet kurz landet man in einem völlig undefinierten state.

**Comment by paflov** [comment]
ich sehe gerade, dass es in diesem Zustand einen "Zur Testheft-Auswahl zurückkehren" Button gibt. Damit ist man in dem Zustand ja nicht völlig verloren. Dennoch müsste man mMn entweder automatisch dorthin zurückkehren oder, eher noch, zur erneueten Eingabe aufgefordert werden, oder?

**Comment by paflov** [comment]
OK, wenn man diesen Button dann clickt kommt:

```
no-unit works!

Flag: end
```
Am restlichen Testheft liegt es aber nicht, denn wenn ich die ganze Freigabewortgeschichte rausnehme kommt das Unit.

**Comment by mechtelm** [comment]
Verstehe ich nicht. Wenn man ein falsches Freigabewort eingibt, passiert nix, d. h. man bleibt auf der aktuellen Seite. Das ist so gewollt. Das ist nicht undefiniert.

**Comment by paflov** [comment]
Ah verstehe... wenn das Freigabewort vor die erste Unit setzt und dann falsch eingibt sieht man eine leere Seite, das wirkte ziemlich undefiniert. Aber nicht so schlimm, wenn der Button oben rechts funktioniert.

**Comment by mechtelm** [comment]
Da bin ich aber erleichtert. Nein die erste Unit sollte man nicht blockieren.

**Comment by paflov** [comment]
Also wenn man das Freigabewort ganz an den Anfang setzt, und dann falsche eingibt ist es Zustand immer noch etwas seltsam (Fragen-Übersichts-Button nicht cllickbar), aber da du das eh nicht vorsiehst, würde ich das Issue als geclosed ansehen.
