### ISSUE TITLE
SysCheck nach gesendetem bericht zumachen?

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#116]
Nur ein Vorschlag: Wenn der SysCheckBericht gesendet wurde, eventuell Erfolg melden und auf die Startseite zurück? Denn was soll man dann noch in dem SysCheck.

**Comment by mechtelm** [comment]
Naja habe die letzte Seite mit einer extra Meldung und einem Button versehen, mit dem man zur SysCheck-Auswahl zurückkommt.
