### ISSUE TITLE
[SysCheck] Questionaire abschaffen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#142]
Statt des Questionaire könnte die Test-Unit selbst benutzt werden.

**Comment by paflov** [comment]
Problem dabei wäre nur, dass wenn die Unit gar nicht geladen wird, man keinerlei Rückmeldung darüber geben könnte. Es sollte vllt. mindestens ein alternatives Eingabefeld geben oder so etwas.

**Comment by mechtelm** [comment]
Questionnaire ist wichtig, um ggf. das Versagen des Players zu berichten.
