### ISSUE TITLE
Ergebnisse Download: Problem mit Zeichenkodierung

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-frontend#162]
Sowohl beim Download von Reviews als auch bei den Antworten werden keine korrekten Csv-Dateien erzeugt: Umlaute sind nicht utf-8-, sondern irgendwie anders kodiert. Unklar, ob das im Frontend oder schon im Backend passiert.

**Comment by paflov** [comment]
Bitte noch mal prüfen. Geht es um Reviews oder SysCheck-Reports?

**Comment by mechtelm** [comment]
Ist unangenehm, kann aber bei der Ergebnisaufbereitung abgefangen werden.

**Comment by mechtelm** [comment]
Dieses Problem unter Windows: Es geht also um den Aufruf von Excel mit diesen Daten unter Windows.
