### ISSUE TITLE
Falsche Meldung auf Menü-Seite

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#190]
# Fehlerbeschreibung

Falsche Meldung auf Menü-Seite: Geht man aus dem laufenden Test ins Menü steht da: "Es wurde kein aktiver Test festgestellt" und es erscheint ein funktionsloser Zurückbutton statt dem Button Test beenden.

```
ggf. Fehler-Ausgabe auf der Browserkonsole
```

# Kontext
**Server**: lokal

**Frontend-Version**: 4.0.0

**Backend-Version**: "5.0.3"

**Testdaten (player etc.)**: IQB Englisch-Test

**Modus**: hot, review

**Browser**: FF

# Screenshot

**Comment by mechtelm** [comment]
Eigentlich ist die Menüfunktion nur eine Spielwiese, gedacht für Review und Demo. Daher ist sie auch standardmäßig ausgeschaltet. Ich habe jetzt trotzdem noch ein bissel gefummelt (#189)
