### ISSUE TITLE
Bei Fokusverlust automatisch pause

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#199]
Es gab mehrfach den Vorschlag einen Test bei Fokusverlust automatisch zu pausieren. Daran hängt aber einiges: Es muss Konfigurierbar sein, nach wie vielen Fokusverlusten oder wie vielen Minuten das passiert.

Beschluss 9.9: Erstmal nicht umsetzen, nur wenn Anforderung konkret formuliert.

**Comment by schnitca** [comment]
In der Besprechung vom 22.09. haben wir beschlossen, auf dieses Feature zu verzichten.
Letztlich ist das Verlassen der Testseite relevant für die Analyiserbarkeit der Daten. Ob das Verlassen der Testseite zum Ausschluss führt, kann/soll die Testleitung entscheiden. Informationen zum Verlassen der Testumgebung werden über das Testsitzungsprotkoll (momentan noch Papierversion) von der Testleitung dokumentiert; in der Codierumgebung sollte die Testleitung eine Empfehlung/Entscheidung zum Ausschluss des Datensatzes von den nachfolgenden Analysen (Tilgung im Zuge der Datenbereinigung) aussprechen können - bzw. wenn wir am IQB die Datenbereinigung vornehmen, sollten wir das aufgrund der Testsitzungsprotokolle (+ Blick auf die Daten) entscheiden. [So wird das momentan auch z. B. bei dokumentierten Audio-Problemen bei Hörverständnisaufgaben gehandhabt, die vom Testsystem nicht geloggt werden können.]
