### ISSUE TITLE
Audio-Player: Pause

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#202]
Problem:
* wird eine unit während des abspielen des Audios pausiert kann es nicht noch mal abgespielt werden
* auch bei vor-zurück: wenn ledliglich das Instruction-Audio gehört wurde, wird das eigentlich das eigentliche Audio als gehört markiert

Prüfen, ob man hier was machen kann.

**Comment by mechtelm** [comment]
Zum ersten Punkt: Können wir erst mit Überarbeitung des Players lösen. Der aktuelle Player reagiert ja nicht auf Pause. Und man kann nicht in die Unit-Daten (restore point) reinfrickeln.

Zum zweiten Punkt: Ist eine Frage der Definition (Editor). Man sollte die Instruction nicht mit 'only once' markieren.

**Comment by paflov** [comment]
Was ist nun mit diesem Ticket?

**Comment by mechtelm** [comment]
Ist in Aspect-Tickets berücksichtigt.
