### ISSUE TITLE
Demo-Modus freigeben

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#204]

**Comment by mechtelm** [comment]
Im Frontend ist Demo vorbereitet - es muss nur vom Backend erlaubt werden (XSD). Backend-seitig sind die Einstellungen identisch mit review, nur dass bei jeder Anmeldung ein neues AuthToken erzeugt wird (mehrere können sich gleichzeitig anmelden).

**Comment by paflov** [comment]
Duplicate https://github.com/iqb-berlin/testcenter-backend/issues/153
