### ISSUE TITLE
[Group-Monitor] Visualisieren, wenn Testperson Browser schließt

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-frontend#206]
Kann der Broadcaster feststellen, ob eine Verbindung zu einem Test noch aktiv ist? Und wenn, kann eine verlorene Verbindung visuell dargestellt werden?

**Comment by paflov** [comment]
Was genau heißt `Verbindnung zum Test`?
a) Ob das Browser-Fenster mit dem Test noch offen ist oder geschlossen wurde
* Damit der Gruppen-Monitor das anzeigen kann, müsste dieses TODO resolved werden: https://github.com/iqb-berlin/testcenter-frontend/blob/f4d32350c535fcda18eb2c8142aa1d90c6317bcf/src/app/test-controller/focus.service.ts#L46
* `navigator.sendBeacon` kann bei schließen eines Browsers noch einen letzten Backend-Call ausführen. Damit müsste man den TestState noch mal schreiben und was entsprechendes hinterlegen.

b)  Ob die Websocket-Verbindung zwischen TestController und Backend besteht - kann der gruppen-Monitor niemals wissen, ist auch egal, da beim Abbruch der Verbdinung in den Polling-Modus übergegenagen wird. Man könnte höchsten nach Modus-Wechsel wiederum einen entsprechenden TestState schreiben...

**Comment by paflov** [comment]
- b) Wäre zu bevorzugen, dreht aber den Informationsfluss um - > geht vermutlich nicht. Falls keine geniale Idee kommt, leider a) umsetzen auch wenn b) bevorzugen wäre.
- auch a) wäre bei genauerer Betrachtung eher aufwendig!
- Browser verlassen soll ein anderer Zustand sein als Fokus-Lost

=> beide Varianten noch mal prüfen, Aufwand abschätzen

(Beschluss, 18.11)
