### ISSUE TITLE
Weiter nach Pause mit nicht gestarteten Heften

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/testcenter-frontend#221]
Um nach dem Pausieren aller Personen den Test wieder fortzusetzen, müssen die nicht aktiven (nicht gestarteten) Hefte explizit abgewählt werden, damit die Aktion durchgeführt werden kann.

**Comment by paflov** [comment]
Die Ursache des Ganzen ist erstaunlich komplex: 

Man kann theoretisch jeden Befehl auch an nicht gestartete tests schicken (was ich auch sinnvoll finde), die werden dann beim Start ausgeführt. Sinn ist, das Leute, die den Browser zugemacht haben / erst später dazu kommen den selben Test-Zustand haben wie alle anderen. 

Der Pause-Button ist clickbar, wenn nur tests angewählt sind, die nicht in der Pause sind, der Resume-Button nur dann, wenn nur tests angewählt sind, die in der Pause sind.

Schicke ich jetzt die Pause an ALLE testhefte, so werden diejenigen, die gerade auch wirklich laufen (= es gibt einen offenen Browser damit) in die Pause versetzt. Die, die nicht laufen, können nicht in die Pause versetzt werden, erst, wenn der Browser (wieder) geöffnet wird. Daher ist der resume-button dann ausgegraut.

Das hat den Vorteil, dass man noch nicht auf Resume drücken kann, wenn noch nicht alle Clients reagiert haben und pause zurückgemeldet.

--

Lösung: die Buttons zu enablen, auch wenn inaktive markiert wurden, dann aber in der Ausführung die inaktiven ignorieren.
