### ISSUE TITLE
Kennworteingabe: Sichtbar oder Whitespace entfernen?

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-frontend#223]
Bei der Kennworteingabe werden nur Bullets dargestellt. Es kam öfters vor, dass Leute das Kennwort aus der E-Mail kopiert haben und nicht merkten, dass sie damit Leerzeichen mitschleiften. Entweder man zeigt die Kennwort-Zeichen wahlweise an oder man löscht standardmäßig Leerzeichen, Tabs und Newlines.

**Comment by paflov** [comment]
Ich würde sogar sagen, beides!

**Comment by paflov** [comment]
wobei Leerzeichen würde ich nicht überall löschen, nur am Anfang und am Ende
