### ISSUE TITLE
Neuer Button: Alle einen Block weiter.

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-frontend#226]
Wenn die Testleitung es geschafft hat, den ersten Block zuzuweisen, vergessen sie meist, die Zielmarkierung für den darauffolgenden Block zu ändern. Es gibt das Gefühl "hatte ja geklappt" und wundern sich, dass die Schüler immer zur ersten Unit desselben Blockes gezwungen werden statt in den nächsten.

**Comment by paflov** [comment]
klingt sinnvoll und lässt sich leicht umsetzen.

**Comment by paflov** [comment]
Stattdessen soll ein neuer Schallter existieren "Alle in den nächsten Block zwingen"
 - der ignoriert Zeilenmarkierungen sondern betrifft IMMER ALLE
 - feststellen, welcher Teilnehmer am weitesten ist. Und alle einen Block weiter zwingen als diesen:

Bsp:

Teilnehmer 1 [x][ ][ ][ ]
Teilnehmer 2 [ ][x][ ][ ]
Teilnehmer 3 [ ][ ][x][ ]
---> alle werden in den 4. Block gezwungen.

(Beschluss 18.11)

**Comment by paflov** [comment]
Neuer Konsens, Besprechung 14.1.21

* Block.-Auswahl über "gleichartige" Testhefte funktioniert wird folgt:
* gleichartig => Blockanzahl auf der obersten Ebene gleich!
* Dann kann man in allen z. B. den 2. Block anwählen (nicht nach Id gehen!)
* Pop-Up über springe zu, das sagt das man etwas anwählen soll
* Beschriftung: springe zu BLOCK-Nummer (statt ID)

Als separates (Ticket) Feature: alle in den nächsten
* in den nächsten hieße (der erste noch von niemandem betretene block)
* für alle buttons nur anbieten, wenn es ermittelbar ist / nur homogene Testhefte gibt
