### ISSUE TITLE
Ansichtsmöglichkeiten reduzieren und Ansicht reduzieren

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-frontend#227]

**Comment by paflov** [comment]
- deutlich zeigen, wenn man nach unten scrollen kann
- Ansicht ändert Logik rausschmeißen
- nur noch mittleere Ansicht behalten, den rest
- spalte "testheft" ausblenden (icons müssen natürlich bleiben)
- stattdessen spalte "block" (testlet) erschaffen
- featured aufgabe weg (und icons woanders hin)
- vertical stauchen

Beschluss 18.11.20

**Comment by paflov** [comment]
Teilaufgaben ausgelagert:
* https://github.com/iqb-berlin/testcenter-frontend/issues/241
* https://github.com/iqb-berlin/testcenter-frontend/issues/242
* https://github.com/iqb-berlin/testcenter-frontend/issues/243
