### ISSUE TITLE
Anzeige von falschem Aufgabentext im Lehrkräftefragebogen

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/testcenter-frontend#231]
Beim Ausfüllen des Lehrkräftefragebogens wurden der Lehrkraft der Testgruppe MSN1 Wörter und Sätze angezeigt, die so nicht in der Aufgabe angelegt waren (siehe Fotos). 

{""browserVersion"":""86"",""browserName"":""Chrome"",""osName"":""Windows 7"",""screenSizeWidth"":1280,""screenSizeHeight"":800,""loadTime"":1184,""appVersion"":""6.3.1""}

![IMG_4234](https://user-images.githubusercontent.com/71453936/96686790-45567380-137f-11eb-9675-27a387e5414d.jpg)
![IMG_4235](https://user-images.githubusercontent.com/71453936/96686793-4687a080-137f-11eb-9c49-d72920154c80.jpg)

**Comment by paflov** [comment]
War nicht reproduzierbar.
