### ISSUE TITLE
Content-Backup-Konzept erarbeiten

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-frontend#263]
Vor riskanten Eingriffen sollte man
* Inhalte (Accounts, Workspaces mit Files und Datenbank-Einträgen, lokale Konfiguration) so sichern, dass man sie ggf. wiederherstellen kann
* Für den Welcome-Screen einen Dummy bereithalten "Wegen Wartungsarbeiten zurzeit blah blah"

Diese Technik könnte man auch nutzen, um Testungen/Befragungen umziehen zu lassen von einem Server zu einem anderen.

**Comment by paflov** [comment]
Ist das wirklich ein Frontend-Ticket?

**Comment by paflov** [comment]
Dies ist wohl eher ein übergreifendes Thema und kein Testcenter-Ticket. Wir schließen es daher.
