### ISSUE TITLE
Besseren Platz für die User-Stories finden

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#269]
Ich hatte mal angefangen user stories für das Testcenter zu schreiben. Diese sollten sowohl für manuelle Tester als auch für das schreiben der e2e-tests als Leitfaden dienen. 

Man müsste mal überlegen, ob die da bleiben sollen wo sie sind (und fertig zu machen wären), oder woanders hinkommen oder gelöscht werden sollen...

https://github.com/iqb-berlin/testcenter-frontend/tree/master/e2e/user-stories

**Comment by tobhu1981** [comment]
Hallo Philipp, danke....schau ich mir mal an. Gruß

**Comment by paflov** [comment]
Hat sich erldiegt
