### ISSUE TITLE
Liste der Testhefte stets beim Betreten der Übersichtsseite neu laden

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-frontend#280]
Die Liste der Testhefte nach dem Einloggen wird nur beim ersten Mal geladen, nicht später beim Navigieren. Das ist z. B. irritierend, wenn der Test beendet wurde und das Frontend auf die Startseite geht. Dann ist der Test nach wie vor enabled und ein Starten fürhrt zum Fehler.

**Comment by paflov** [comment]
Dies war offenbar bereits der Fall. Ich vermute das irritierende Verhalten trart eher auf, weil die Testliste neu geladen wurde, bevor der test gesperrt wurde. Dies sollte in zukünftigen Versionen behoben sein.
