### ISSUE TITLE
[SysCheck] Erwartete Mindest-Browser-Versionen über XML konfigurieren

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#32]
- Text "Netzprofil nicht verfügbar weil Browser veraltet " nicht rot
- nicht beantwortete Fragen nicht rot machen
- veraltete Browser-Versionen konfigurierbar über XML

**Comment by schnitca** [comment]
Nicht beantwortete Fragen können meinetwegen ruhig rot markiert werden; dann aber bitte in dem Text darüber erläutern:
Fragen (nicht beantwortete Fragen rot markiert)

**Comment by mechtelm** [comment]
Einfärbungen sind beseitigt, aber das mit der Browserversion ist noch nicht geklärt.

**Comment by paflov** [comment]
hat sich erledigt
