### ISSUE TITLE
Darstellungen Navigationsleiste Testcenter auf Tablet

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#349]
Nur mal für die Zukunft, wenn du dich mal mit dem Thema Tablets beschäftigen wirst. BW hatte schon ein bißchen mit Tablets rumgespielt und uns eine Liste mit Dinge zukommen lassen, die ihnen aufgefallen waren. Darunter auch ein Punkt, der für dich interessant sein könnte. Das ist wohl an einem iPad mit Safari aufgetreten:
![grafik](https://user-images.githubusercontent.com/78656991/153429823-d590ea9d-ffc3-48b4-b0e1-8ed00ca993b4.png)

**Comment by paflov** [comment]
Was ist hier der Kontext? 
Also welche Booklet-Parameter sind gesetzt? Damit ich weiß, was überhaupt erreicht werden soll.

**Comment by tobhu1981** [comment]
Gute Frage. Ich weiß es nicht mehr. Der Punkt war hier nur gelandet damit das Thema nicht untergeht. Die haben ja nun schon vieles mit Tablets gemacht, auch schon eine Pilotierung und dabei sind relativ wenig Fehler bzgl. Tablet aufgetreten. Von diesem speziellen Verhalten habe ich nie wieder gehört. Außerdem wurden inzwischen mehrmals die Player-, Editor-, Testcenterversionen geändert und es gibt mittlerweile klare Ansagen seitens IQB bzgl. welche Browserversionen unterstütz werden und welche nicht. Ich könnte mir vorstellen, dass hier vielleicht auch eine steinalte Safari-Version verwendet wurde. Daher würde ich das Ticket mal als erledigt betrachten.
