### ISSUE TITLE
TLK: springe zu Unit

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#356]
Vorschlag kommt vom IBBW:

St: Idee für neues Feature:

Springen zu Block_X ist aktuell möglich durch TLK
Springen in Unit_Y nicht
Grund? wird das zweite später auch implementiert?

**Comment by paflov** [comment]
MM hat seinerzeit gegen dieses Feature entschieden. Es wäre auch eine hart Vierkomplizierung nicht nur des Codes sondern auch der UI...

**Comment by paflov** [comment]
MM hat seinerzeit gegen dieses Feature entschieden. Es wäre auch eine hart Vierkomplizierung nicht nur des Codes sondern auch der UI...
