### ISSUE TITLE
Im Demo-Modus läuft der timer weiter, wenn ein zeitgesteuerter Block verlassen wird

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#358]
# Fehlerbeschreibung

Im Demo-Modus läuft der timer weiter, wenn ein zeitgesteuerter Block verlassen wird

Original-Beschreibung voon FS/IBBW:

1.

> Die Lehrkraft hat sich angemeldet und hat auf „Test ansehen“ geklickt, damit sie weiß, was auf die SuS am Testtag zukommt.
> Die Lehrkraft ist im Lesegeschwindigkeits-Speedtest (es ist in unserem Testheft der einzige Block mit Zeit-constraint). Timer zählt runter. alles wunderbar.
> ![a1](https://user-images.githubusercontent.com/12844833/158133175-65a38642-fb71-45bf-8f46-89797eab0dba.png)
> 
> Die Lehrkraft ist schon mit dem LG-Speedtest fertig ist und blättert weiter.
> Der Timer zählt weiter herunter.
> 
> ![a2](https://user-images.githubusercontent.com/12844833/158133298-b4f1c2fc-c108-40ea-8654-db7416ac5bd0.png)
> 
> ![a3](https://user-images.githubusercontent.com/12844833/158133410-dd5e143a-140f-4510-aab0-23fdce777332.png)
> 
> Eigentlich sollte der Timer aufhören, sobald die Lehrkraft den Speedtest-Block verlässt. Oder irre ich mich da?
> (Falls jetzt ein weiterer Block mit Zeit-constraint käme, was würde passieren?)
> 
> Haben Sie eine Vermutung, womit dieses Verhalten zusammen hängen könnte?
> Könnten Sie das bitte prüfen?

Prüfung hat ergeben: Dies betrifft nicht den Hot-Modus.

# Kontext
**Server**: IBBW

**Version**: 12.1.0@12.2.1

**Comment by tobhu1981** [comment]
Da bin ich mir unsicher wie ich das prüfen soll. Hier läuft ja dein Speedtest-Player oder? Siehst du eine Möglichkeit das vor dem Update selbst noch einmal durchzuspielen? Vielleicht kannst du mir bei Gelegenheit mal zeigen worauf ich da zu achten haben.

**Comment by paflov** [comment]
Das hat mit dem Player eigentlich nix zu tun gehabt, es war einfach so, dass die Zeit weiter lief wenn man einen Zeitbeschränken Block verlassen hat. Ist jetzt aber eindeutig gefixed.
