### ISSUE TITLE
PresentationProgress und ResponseProgress funktionieren nicht im Demo-Modus 

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#359]
# Fehlerbeschreibung

PresentationProgress und ResponseProgress funktionieren nicht im Demo-Modus. Es wird immer die Meldung angezeigt, dass man nicht weiterblättern dürfte.

Originalmeldung von FS/IBBW:

> Während die Lehrkraft durch den LG-Speedtest klickt (egal, ob sie Aufgaben bearbeitet oder auf den weiter-Button klickt), kommt bei jeder neuen Seite die Meldung „Im Testmodus dürfte hier nicht weiter geblättert werden: Es wurde nicht alles bearbeitet“.
> Die Warnmeldung gilt eigentlich nur für den Fall, dass der Weiter-Button geklickt wird. (Falls die Aufgabe bearbeitet wird, passt ja alles.)

# Kontext
**Server**: IBBW

**Version**:12.1.0@12.2.1

**Comment by tobhu1981** [comment]
Es kommt derzeitg gar keine Meldung, auch wenn Pflichtfelder nicht ausgefüllt wurden. Hat wahrscheinlich die gleiche Ursache wie beim Ticket #377

**Comment by tobhu1981** [comment]
Funktioniert jetzt.
