### ISSUE TITLE
Modus: run-demo: Anzeige verbleibende Zeit

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#361]
TH:
Auch wenn ``unit_show_time_left`` = OFF ist, soll die herunterlaufende Zeit bei parametrierter Zeitbeschränkung angezeigt werden. Die Zeit wird aber nicht angezeigt.

**Comment by paflov** [comment]
Kann ich nicht bestätigen.

**Comment by tobhu1981** [comment]
Hmm...habe es gerade noch einmal mit einem Demo-Test probiert. In der Instanz: https://testcenter.iqb.hu-berlin.de wird mir keine Restzeit angezeigt. Ich sehe nur unten beim Betreten des zeitbeschränkten Bereichs eine kurze Meldung bzgl. der Bearbeitungszeit.
In meinem Arbeitsbereich (Tobias) liegt der Demotest drin mit dem ich es probiert habe. Du müsstest ja Zugriff haben.

**Comment by tobhu1981** [comment]
Zeit wird leider nach wie vor nicht angezeigt.

**Comment by paflov** [comment]
Schau mal [hier](https://github.com/iqb-berlin/testcenter-frontend/blob/master/docs/test-mode.md):
Bei DEMO ist kein X bei "_Sollte eine Maximalzeit für einen Testabschnitt festgelegt sein, wird die verbleibende Zeit angezeigt, auch wenn die Booklet-Konfiguration dies unterbindet._" 
Es soll also im Demo-Modus auch gar keine Zeit angezeigt werden, wenn nicht _unit_show_time_left_ gesetzt ist.

Das Testcenter verhält sich also korrekt.

Das war tatsächlich auch mal anders. Schau [hier](https://github.com/iqb-berlin/testcenter-frontend/blob/master/CHANGELOG.md#1203):
Änderung in Version 12.0.3 "_In "demo" mode "showTimeLeft" is off now_". Ich habe das offenbar es absichtlich geändert. Und zwar am 8.2.22. Leider weiß ich überhaupt nicht mehr warum!

**Comment by paflov** [comment]
Wegen dieser Anforderung: https://github.com/iqb-berlin/testcenter-frontend/issues/319

**Comment by tobhu1981** [comment]
Tja das passiert dann wohl, wenn man auf der falschen Seite sucht. In meinem Bildchen im Wiki ist das Kreuz nämlich noch drin. Heißt ich muss das mal an deinen Stand angleichen und damit auch leider auch Testskripte.
