### ISSUE TITLE
TLK: Anzeige eines Logins, obwohl dieser gelöscht wurde

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#366]
Testcenter version 12.1.0@12.2.2
TH: Broadcasting-Service flashen, wenn Login-Datei geändert.

**Comment by paflov** [comment]
Ansonsten erscheinen gelöschte User noch im Gruppen-Monitor und es passieren alle möglichen komischen Dinge...

**Comment by paflov** [comment]
in Backend 12.3.2 erledigt, auf dem Testsystem zu testen.

**Comment by tobhu1981** [comment]
Funktioniert!
