### ISSUE TITLE
CustomText "booklet_codeToEnterPrompt" lässt sich nicht ändern

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#369]
Testcenter version 12.1.0@12.2.2
TH: Es müsste noch einmal geprüft werden, ob alle Textersetzungen, die über das TC (System-Admin) gesetzt werden können, die richtigen Stellen beschreiben. Ein CustomText scheint nicht zu funktionieren und zwar: booklet_codeToEnterPrompt: 
Aufforderung für die Eingabe eines Freigabewortes (Dialog-Box). Der im TC dafür angegebene Text entspricht nicht dem Text, der in der Dialogbox angezeigt wird. Eine Änderung des Textes ist nicht möglich.

**Comment by paflov** [comment]
Ah, das ist ein wenig Tricky.

Der Text von "booklet_codeToEnterPrompt" findet nur Verwendung, wenn im Booklet nicht etwas anderes angegeben ist 

`<CodeToEnter` code="aaa" ></CodeToEnter>`

oder

`<CodeToEnter` code="aaa"  />`

Bei 

`<CodeToEnter` code="aaa"  >HALLO</CodeToEnter>`

Wäre HALLO der Text.

**Comment by tobhu1981** [comment]
Ah....sehr gut. Muss man wissen. Dann können wir das Ticket schließen.
