### ISSUE TITLE
Freigabewort wird verlangt trotz Freigabe durch Testleitungskonsole

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/testcenter-frontend#379]
# Fehlerbeschreibung

Die Testleitungskonsole kann den Testtaker zwar in den nächsten Block schieben, aber der Testtaker sieht statt der Aufgabe weiterhin das Pop-up, das nach dem Freigabewort verlangt.

```
Fehler-Ausgabe auf der Browserkonsole siehe Screenshot
```

# Kontext
**Server**: OCBA / Local / etc.
https://testcenter.iqb.hu-berlin.de/

**Frontend-Version**:
IQB-Testcenter version 12.1.2@12.2.3

**Backend-Version**: 
?

**Testdaten (player etc.)**:
v1.29/v1.23

**URL**: 
https://testcenter.iqb.hu-berlin.de/

**Modus**:
monitor-group/run-hot-return

**Browser**: 
Firefox 9.0.1 (64-Bit)/Chrome 100.0.4896.127 (Offizieller Build) (64-Bit)

# Screenshot
links Testtaker, rechts Konsole:
![grafik](https://user-images.githubusercontent.com/71453936/164619707-645b79f5-622f-4d57-a616-15de25c04fc1.png)
Browserkonsole Testtaker:
![grafik](https://user-images.githubusercontent.com/71453936/164619748-8a622bb6-7ad2-4b6e-9a94-17240f256d7a.png)
Browserkonsole Testleitung (keine Fehler):
![grafik](https://user-images.githubusercontent.com/71453936/164619776-52072d35-d85e-4479-9c16-82beb627bda1.png)

**Comment by tobhu1981** [comment]
Habe ich getestet. Freigabewort wird nun nicht mehr verlangt, man gelangt direkt in den Block.
