### ISSUE TITLE
Bezeichnung Aufgabe im Browsertab änderbar

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#381]
IQB-Testcenter version 12.1.2@12.2.3
TH: Vielleicht könnte man den Namen einer Aufgabe im Browsertab änderbar machen.
![grafik](https://user-images.githubusercontent.com/78656991/165042525-efc69c8d-6a05-42c1-b31f-a2ebf0f27812.png)

**Comment by paflov** [comment]
Siehe iqb-berlin/testcenter#91
