### ISSUE TITLE
Test verlassen vor vollständiger Betrachtung bzw. Bedienung

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#382]
IQB-Testcenter version 12.1.2@12.2.3
Ist `presentation complete` oder `response complete` aktiv, soll es nicht möglich sein den Test zu verlassen, wenn diese Bedingungen nicht erfüllt sind. Derzeitig kann eine Hot-Testungen mit diesen aktiven Bedingungen aber verlassen werden.

**Comment by tobhu1981** [comment]
Aktuell kann der Test beendet werden, auch wenn Pflichtfelder nicht bearbeitet wurden. Jenny meinte ja eigentlich, dass das nicht so ein soll, oder habe ich da was missverstanden?

**Comment by paflov** [comment]
Richtig verstanden. Aktuell auf testcenter.iqb.hu-berlin.de ist 12.1.6@12.3.3 deployed, da sollte das eigentlich geändert sein. Könntest du bitte bestätigen, und dann das Ticket schließen bei Gelegenheit.

**Comment by tobhu1981** [comment]
Ah okay, hatte es auf unserer Produktivinstanz versucht. Es scheint für `response complete` zu funktionieren, aber für `presentation complete` nicht. Ich habe 3 Units in einem zugangsbeschränkten Block. Nur in der ersten Unit befinden sich Pflichtfelder. Solange ich diese nicht bediene kann ich den Test nicht beenden. Soweit richtig. Wenn ich diese Felder ausgefüllt habe kann ich allerdings den Test beenden ohne die restlichen folgenden beide Units gesehen zu haben.

**Comment by paflov** [comment]
PresentationComplete und ResponseComplete werden nur für die aktuelle Unit ermittelt. Über weiter vorne liegende Units kann man nichts sagen, insofern wüsste ich nicht, wie es sich hier anders verhalten sollte?

PresentationComplete bezieht sich darauf dass man _alle Seiten einer Unit_ geöffnet und bis nach unten gescrolled hat, nicht darauf das man alle Units eines Blocks gesehen hat. Letzteres wäre ein ganz neue Anforderung.

**Comment by tobhu1981** [comment]
Ja `presentation_complete` bezieht sich immer nur auf die aktuelle Unit. Ich hatte aber gedacht, dass du übergeordnet verhinderst den Test zu verlassen, wenn noch nicht alle Units eines Blocks aufgerufen wurden (also unabhängig von `presentation_complete` der sich dann nur auf die Unit direkt bezieht) **und** noch nicht alle Plichfelder in den Units bearbeitet wurden. Im MOment wird ein Abbruch verhindert, wenn man sich in einer Unit mit nicht bearbeiteten Pflichfeldern befindet, finde ich auch soweit logisch. Wenn ein Testabbruch unter dieser Bedingung verhindert werden soll, müsste sich das doch auf alle Units mit Pflichfelder innerhalb eines Blocks beziehen, oder? Und um zu überprüfen, ob es noch Pflichtfelder in einer der Units gibt, müssten sie einmal aufgerufen werden. Aber vielleicht verstehe ich da die Anforderungen nicht so recht.

**Comment by paflov** [comment]
Tja was du beschreibst erscheint irgendwie logisch, wurde so aber nie als Anforderung beschriben. Ich schließe das Ticket erstmal, sie werden schon auf uns zukommen, wenn sie es so haben wollen.
