### ISSUE TITLE
presentation complete verlangt Beantwortung von Fragen

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/testcenter-frontend#387]
IQB-Testcenter version 12.1.5@12.2.3

Wenn man innerhalb einer Unit keine Fragen beantwortet hat, wird man durch "presentation complete" Warnmeldung am Weiterklicken gehindert. Keine der Fragen ist als Pflichtfeld definitert, daher sollte es möglich sein, auch ohne Beantwortung weiterzuklicken, solange man alles angesehen hat.

**Comment by paflov** [comment]
Könntest du bitte die entsprechende Unit hier anhängen oder mir sagen, wo ich sie finden kann? Ich nehme an, das ist kein allgemeines Problem.

**Comment by tobhu1981** [comment]
Das hatten wir doch eigentlich schon getestet. In meinem angelegten hot-Test kann ich auch ohne Beantwortung weiterblättern, solange ich alles gesehen und gehört habe. Auch wenn es Pflichtfelder gibt und `response_complete=OFF` und nur `presentation_complete=ON` ist, kann ich weiterblättern auch ohne Beantwortung.

**Comment by PaulineKohrt** [comment]
Hier sind einige von den Units bei denen das passierte:
[2022-05-13 UnitDefs.voud.zip](https://github.com/iqb-berlin/testcenter-frontend/files/8688197/2022-05-13.UnitDefs.voud.zip)

**Comment by paflov** [comment]
Hi, ich hab mir mit Tobias das Ticket noch mal genau angesehen und auch die Units getestet. Wir sind zu dem Schluss gekommen, dass sich das Testcenter korrekt verhält (ich hatte vorher nicht genau gelesen).

> Wenn man innerhalb einer Unit keine Fragen beantwortet hat, wird man durch **"presentation complete"** Warnmeldung am Weiterklicken gehindert. Keine der Fragen ist als Pflichtfeld definitert, daher sollte es möglich sein, auch ohne Beantwortung weiterzuklicken, solange man alles angesehen hat.

**PresentationComplete** gibt an ob *alle Seiten innerhalb der Unit* angesehen (d. .h. nach unten gescrolled) wurden und alle verpflichtenden Audios/Videos angesehen wurden. Ob es Pflichtfelder gibt oder nicht ist dabei vollkommen unerheblich. Ob alle Pflichtfelder ausgefüllt worden sind gibt **ResponseComplete** an. 

Wenn ihr wollt, dass bei diesen Aufgaben auf jeden Fall weiterlicken können soll, ohne irgendwas gemacht zu haben, dann müsste auch auch force_response_complete auf OFF stellen.

**Comment by paflov** [comment]
Wenn von euch kein Veto kommt, schließe ich das Ticket.

**Comment by PaulineKohrt** [comment]
Im Booklet sind folgende beide Zeilen enthalten: 
  <Config key="force_presentation_complete">ON</Config>
  <Config key="force_responses_complete">OFF</Config>

Das Problem ist also nicht durch die Bookleteinstellung entstanden. Bitte das Ticket noch nicht schließen.

**Comment by paflov** [comment]
Nach Klärung mit PK: Das Problem war, dass die Aufgaben nach unten gescrolled worden waren, aber prensentationComplete trotzdem nicht angenommen wurde. Ob mit der Beantwortung der Fragen ein Zusammenhang besteht ist nicht klar.

**Comment by PaulineKohrt** [comment]
und jetzt fällt mir erst ein, dass wir beide Fälle schon hatten
1) sowie du gerade beschrieben hast (unabhängig davon ob eine Frage beantwortet wurde kann man nicht weiter klicken und die presenation complete Meldung erscheint, auch wenn man bis runter gescrollt hat)
2) man kann nicht weiter klicken (presenation complete Meldung erscheint) obwohl bis runter gescrollt wurde, wenn man aber ein Item bearbeitet, kommt man weiter.
