### ISSUE TITLE
Testdateien im Zip-Format laden: Fehlerhafte Duplikaterkennung

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#388]
# Fehlerbeschreibung

Werden die Testdateien alle zusammen mittels Zip-Datei in das Testcenter geladen, scheint sich das Testcenter auf immer und ewig die auf diese Weise geladene Testtakers.xml zu merken, auch wenn diese wieder gelöscht wurde.

Ablauf:

Laden aller Testdateien als Zip. Anschließendes Löschen der so mit geladenen Testtakers.xml im Testcenter. Laden einer neuen Testtakers.xml mit anderem Groupnamen und anderen Logins. Soweit alles gut. Wird jetzt aber versucht noch einmal die Testtakers.xml aus dem Zip-Paket einzeln zu laden, meldet das TC, dass Logins und die Group bereits vorhanden sind, obwohl die ursprüngliche Testtakers ja gar nicht mehr existiert. In der Fehlermeldung wird dann auch gesagt, dass es einen Konflikt mit der Testtakers.xml aus dem ursprünglich geladenen Zip-Paket gibt. 

# Kontext
IQB-Testcenter version 12.1.6@12.3.3

# Screenshot

**Comment by paflov** [comment]
Fixed in BE 12.0.4
