### ISSUE TITLE
Chrome Erweiterung versteckt Seiteninhalte

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/testcenter-frontend#401]
Zur Dokumentation:

Aufgabeninhalte ploppten kurz auf und verschwanden sofort wieder.

Chrome Version 102.0.5005.63 (Offizieller Build) (64-Bit)

Durch Entfernen einer Erweiterung (Urban VPN proxy Unblocker) konnte der Fehler behoben werden.

**Comment by paflov** [comment]
Lieber Tobias,
magst du diese Info im Wiki irgendwo an geeigneter Stelle vermerken (gibt es Troubleshooting?). Wir wissen nicht, was wir sonst hier machen sollen xD
Danach gerne das Ticket schließen.

**Comment by tobhu1981** [comment]
Hab ich im Wiki unter FAQ ablegt.
