### ISSUE TITLE
Fehler Speicherung mehrere Logs

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-frontend#406]

**Comment by tobhu1981** [comment]
IQB-Testcenter version 12.1.9@12.4.2

Meldung aus BW: Sollen Logs aus mehreren Testungen gemeinsam gespeichert werden kommt es zu einem Fehler in der Logdatei. Dort steht dann folgendes drin: 
```xml
<br />
<b>Fatal error</b>: Maximum execution time of 30 seconds exceeded in <b>/var/www/html/classes/helper/CSV.class.php</b> on line <b>96</b><br />
```
Bei der Speicherung einzelnen Logs tritt der Fehler nicht auf.

**Comment by jkoelm** [comment]
Bei uns tritt genau das auch auf, wenn man nur die Logs einer einzelnen Testung runterladen will. Bei mehreren Testgruppen ist das, was in der ausgegebenen csv steht, ein bisschen anders: 

```
> <br />
> <b>Fatal error</b>:  Allowed memory size of 134217728 bytes   exhausted (tried to allocate 4096 bytes) in   <b>/var/www/html/classes/dao/DAO.class.php</b> on line   <b>68</b><br />
```

**Comment by jkoelm** [comment]
Eine Konkretisierung: Am 02.06. funktionierte es noch normal, danach kam ein Update, an dem es wohl liegt, ab 08.06. geht es nicht mehr.

**Comment by tobhu1981** [comment]
Nach wie vor scheint hier ein Problem vorzuliegen, auch beim Laden eines einzelnen Files.

**Comment by paflov** [comment]
Issue moved to [iqb-berlin/testcenter #107](https://github.com/iqb-berlin/testcenter/issues/107) via [**Zenhub**](https://www.zenhub.com/)
