### ISSUE TITLE
Anwendung sperren, wenn Backend Version nicht stimmt

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#53]
In der refaktorisierten Version liefert der Endpoint `[GET] system/config` (vorher `[GET] /sysconfig) auch eine Versions-nummer aus. Wenn Frontend- und Backend-Version nicht übereinstimmen soll die Anwendung gesperrt werden.

**Comment by paflov** [comment]
Ich habe jetzt Backend-Version 3.1.1
und im Frontend steht: "Erforderliche Version der Server-Programmierung: 3.0.1" 
und es funktioniert nicht trotzdem - obwohl die mittlere Zahl abweicht. Ist das korrekt?

**Comment by paflov** [comment]
Ich würde noch einmal diskutieren wollen ob im Falle eines Server-Fehlers oder eines anderen schweren Fehlers sich die Anwendung nicht komplett sperren sollte, anstatt das nur die rot-weiße Fehlermeldung erscheint und die Anwendung in einem unklaren State hinterlässt.

**Comment by mechtelm** [comment]
Anwendung wird gesperrt, wenn API-Version nicht stimmt.
