### ISSUE TITLE
XSD Doku

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-frontend#81]
* XSDs sollen dokumentiert werden
* reicht es als Annotationen, oder gibt es einen besseren Weg? -> Prüfen
* am besten mit/ nach der nächsten großen XSD Änderung angehen

**Comment by paflov** [comment]
Beispieldateien im backend /sampledate

**Comment by mechtelm** [comment]
Achtung: Beispiele pflegen; Auch: MarkDown-Texte hinterlegen zur Einstimmung

**Comment by paflov** [comment]
Videos!
